server:
  port: 8078

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: postgres
    password: example
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/javadb
